apiVersion: v2
name: externaldns-coredns
description: A Helm chart for deploying ExternalDNS with CoreDNS and etcd

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.11.1"

dependencies:
- name: etcd
  version: "9.15.2"
  repository: "https://charts.bitnami.com/bitnami"

- name: external-dns
  version: "6.36.1"
  repository: "https://charts.bitnami.com/bitnami"

- name: coredns
  version: "1.36.0"
  repository: "https://coredns.github.io/helm"
